### ISSUE TITLE
$ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by privefl** [yonicd/issue#1]
Running 
```
library(issue)
x <- issue::get_issues(repo = 'r-lib/pkgdown',
                       last = 20)%>%
    issue::create_table()
```
I get 
> Error: $ operator is invalid for atomic vectors

**Comment by yonicd** [comment]
do you have a github personal access token set up?

**Comment by privefl** [comment]
I don't.

**Comment by yonicd** [comment]
This package relies heavily on the querying the github api. you can create a personal access token (PAT) with [usethis](https://usethis.r-lib.org/reference/browse_github_pat.html). 

After setting up the PAT as a system variable, you can write out the call more explicitly.

```r
issue::get_issues(
  repo = 'r-lib/pkgdown',
  last = 20,
  PAT = Sys.getenv('GITHUB_PAT') # or whatever you called it
) 
```

**Comment by privefl** [comment]
Maybe you should explain this in the README.

**Comment by yonicd** [comment]
thank you for the suggestion.
